In [6]:
import pandas as pd

data_path = '../../datasets/Dataset_dummy_v2.csv'
data_sampah = pd.read_csv(data_path)
data_sampah['tanggal'] = pd.to_datetime(data_sampah['tanggal'])

# Simpan variabel ke dalam storage
%store data_sampah

Stored 'data_sampah' (DataFrame)

In [4]:
import pandas as pd

# Gunakan path relatif dari lokasi notebook atau script Anda
data_path = '../../datasets/Dataset_dummy_v2.csv'

# Membaca data dari file CSV
data_sampah = pd.read_csv(data_path)
#groupping kecamatan
grouping_kecamtan = data_sampah.groupby('kecamatan')

andir = grouping_kecamtan.get_group('Andir')
astana_anyar = grouping_kecamtan.get_group('Astana Anyar')
antapani = grouping_kecamtan.get_group('Antapani')
arcamanik = grouping_kecamtan.get_group('Arcamanik')
babakan_ciparay = grouping_kecamtan.get_group('Babakan Ciparay')
bandung_kidul = grouping_kecamtan.get_group('Bandung Kidul')
bandung_kulon = grouping_kecamtan.get_group('Bandung Kulon')
bandung_wetan = grouping_kecamtan.get_group('Bandung Wetan')
batununggal = grouping_kecamtan.get_group('Batununggal')
bojongloa_kaler = grouping_kecamtan.get_group('Bojongloa Kaler')
bojongloa_kidul = grouping_kecamtan.get_group('Bojongloa Kidul')
buahbatu = grouping_kecamtan.get_group('Buahbatu')
cibeunying_kaler = grouping_kecamtan.get_group('Cibeunying Kaler')
cibeunying_kidul = grouping_kecamtan.get_group('Cibeunying Kidul')
cibiru = grouping_kecamtan.get_group('Cibiru')
cicendo = grouping_kecamtan.get_group('Cicendo')
cidadap = grouping_kecamtan.get_group('Cidadap')
cinambo = grouping_kecamtan.get_group('Cinambo')
coblong = grouping_kecamtan.get_group('Coblong')
gedebage = grouping_kecamtan.get_group('Gedebage')
kiaracondong = grouping_kecamtan.get_group('Kiaracondong')
lengkong = grouping_kecamtan.get_group('Lengkong')
mandalajati = grouping_kecamtan.get_group('Mandalajati')
panyileukan = grouping_kecamtan.get_group('Panyileukan')
rancasari = grouping_kecamtan.get_group('Rancasari')
regol = grouping_kecamtan.get_group('Regol')
sukajadi = grouping_kecamtan.get_group('Sukajadi')
sukasari = grouping_kecamtan.get_group('Sukasari')
sumur_bandung = grouping_kecamtan.get_group('Sumur Bandung')
ujung_berung = grouping_kecamtan.get_group('Ujungberung')

          id     tanggal    kecamatan  jumlah_sampah satuan
7          8    1/1/2016  Ujungberung            1.1    TON
39        40    1/3/2016  Ujungberung            1.6    TON
61        62    1/4/2016  Ujungberung            2.4    TON
86        87    1/5/2016  Ujungberung            1.9    TON
97        98    1/5/2016  Ujungberung            2.6    TON
...      ...         ...          ...            ...    ...
73830  73831  11/26/2023  Ujungberung            6.1    TON
73866  73867  11/27/2023  Ujungberung            5.8    TON
73891  73892  11/28/2023  Ujungberung            5.2    TON
73915  73916  11/29/2023  Ujungberung            5.5    TON
73943  73944  11/30/2023  Ujungberung            6.1    TON

[2590 rows x 5 columns]

In [13]:
var_kecamatan = ["Andir","Astana Anyar","Antapani","Arcamanik","Babakan Ciparay","Bandung Kidul","Bandung Kulon","Bandung Wetan","Batununggal",
    "Bojongloa Kaler","Bojongloa Kidul","Buahbatu","Cibeunying Kaler","Cibeunying Kidul","Cibiru","Cicendo","Cidadap","Cinambo","Coblong","Gedebage",
    "Kiaracondong","Lengkong","Mandalajati","Panyileukan","Rancasari","Regol","Sukajadi","Sukasari","Sumur Bandung","Ujungberung"
]

list_grup_kecamatan = [andir,astana_anyar, antapani,arcamanik,babakan_ciparay,bandung_kidul,bandung_kulon,bandung_wetan,batununggal,bojongloa_kaler,bojongloa_kidul,buahbatu,
                       cibeunying_kaler,cibeunying_kidul,cibiru,cicendo,cidadap,cinambo,coblong,gedebage,kiaracondong,lengkong,mandalajati,panyileukan,rancasari,regol,sukajadi,
                       sukasari,sumur_bandung,ujung_berung
                       ]